## Multilinear Regression

### Perform prediction on mtcars.csv dataset for mileage per gallon using multiple inputs like disp,hp,wt vehicle. Use multilinear regression for the same.

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
data=pd.read_csv('mtcars.csv')

In [3]:
data.head()

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2

In [4]:
#independant
x=data.loc[:,['disp','hp','wt']]

In [5]:
type(x)

pandas.core.frame.DataFrame

In [9]:
x[:4]

disp   hp     wt
0  160.0  110  2.620
1  160.0  110  2.875
2  108.0   93  2.320
3  258.0  110  3.215

In [5]:
y=data.loc[:,'mpg']

In [7]:
y[:4]

0    21.0
1    21.0
2    22.8
3    21.4
Name: mpg, dtype: float64

## Split the dataset

In [6]:
from sklearn.model_selection import train_test_split

In [ ]:
train_test_split()

In [7]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=10)

In [22]:
x_train

disp   hp     wt
19   71.1   65  1.835
14  472.0  205  5.250
18   75.7   52  1.615
6   360.0  245  3.570
11  275.8  180  4.070
23  350.0  245  3.840
24  400.0  175  3.845
30  301.0  335  3.570
22  304.0  150  3.435
10  167.6  123  3.440
27   95.1  113  1.513
31  121.0  109  2.780
8   140.8   95  3.150
26  120.3   91  2.140
16  440.0  230  5.345
25   79.0   66  1.935
17   78.7   66  2.200
0   160.0  110  2.620
15  460.0  215  5.424
4   360.0  175  3.440
29  145.0  175  2.770
9   167.6  123  3.440

### Training

In [8]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

### prediction

In [27]:
x_test

disp   hp     wt
20  120.1   97  2.465
7   146.7   62  3.190
5   225.0  105  3.460
2   108.0   93  2.320
3   258.0  110  3.215
21  318.0  150  3.520
13  275.8  180  3.780
28  351.0  264  3.170
12  275.8  180  3.730
1   160.0  110  2.875

In [9]:
y_pred=model.predict(x_test)

In [25]:
y_pred

array([25.28711545, 23.60858749, 21.15602393, 25.99128696, 22.0195312 ,
       19.50236139, 17.36100552, 17.03952708, 17.56248048, 23.24620595])

In [26]:
y_test

20    21.5
7     24.4
5     18.1
2     22.8
3     21.4
21    15.5
13    15.2
28    15.8
12    17.3
1     21.0
Name: mpg, dtype: float64

In [10]:
model.score(x_train,y_train)*100

85.65810714482754

### Scalling of the data

In [11]:
from sklearn.preprocessing import StandardScaler   #(x-mean)/std.
sc_x=StandardScaler()

In [30]:
x_train[:4]

disp   hp     wt
19   71.1   65  1.835
14  472.0  205  5.250
18   75.7   52  1.615
6   360.0  245  3.570

In [12]:
x_train=sc_x.fit_transform(x_train)

In [13]:
x_train[:4]

array([[-1.19263405, -1.21776482, -1.2556939 ],
       [ 1.74516619,  0.7428811 ,  1.80164423],
       [-1.15892519, -1.39982479, -1.45265273],
       [ 0.92442879,  1.30306564,  0.29759502]])

In [14]:
sc_y=StandardScaler()
y_train=sc_y.fit_transform([y_train])

In [15]:
x_train.shape

(22, 3)

In [16]:
y_train.shape=(22,1)

In [17]:
len(x_train)

22

In [53]:
len(y_train)

22

In [18]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [19]:
model.score(x_train,y_train)*100

100.0

In [ ]:
x_test=sc_x.transform(x_test)

# predict the test set result


In [20]:
x_test

disp   hp     wt
20  120.1   97  2.465
7   146.7   62  3.190
5   225.0  105  3.460
2   108.0   93  2.320
3   258.0  110  3.215
21  318.0  150  3.520
13  275.8  180  3.780
28  351.0  264  3.170
12  275.8  180  3.730
1   160.0  110  2.875

In [21]:
y_pred=model.predict(x_test)

In [22]:
y_pred,y_test

(array([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]]),
 20    21.5
 7     24.4
 5     18.1
 2     22.8
 3     21.4
 21    15.5
 13    15.2
 28    15.8
 12    17.3
 1     21.0
 Name: mpg, dtype: float64)

In [24]:
print('Accuracy',model.score(x,y)*100)
print('Coefficient:',model.coef_) #slope
print('Intercept:',model.intercept_) #intercept

Accuracy -1147.0445427048323
Coefficient: [[0. 0. 0.]]
Intercept: [0.]


#  new sample prediction

In [23]:
x_new=np.array([[221,102,2.91]])
y_new=model.predict(x_new)
print(y_new)

[[0.]]


In [ ]:
(221*(-9.37009081e-04))+(102*(-3.11565508e-02))+(2.91*(-3.80089058e+00))+37.10550526903182